/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdminRole;


import Sports.DB40Util.DB4OUtil;
import Sports.EcoSystem;
import Sports.User.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.time.LocalTime;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


/**
 *
 * @author anveshvarma
 */
public class AdminWorkspace extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkspace
     */
    JPanel container;
    EcoSystem ecosystem;
    UserAccount userAccount;
    DB4OUtil db = DB4OUtil.getInstance();
    public AdminWorkspace(JPanel container, UserAccount ua,EcoSystem ecosystem) {
        initComponents();
        this.ecosystem = ecosystem;
        this.container = container;
        this.userAccount = ua;
        date.setText(" "+String.valueOf(LocalTime.now().getHour()) + ":"+String.valueOf(LocalTime.now().getMinute()));
        lblAdminIcn.setIcon(new ImageIcon(new ImageIcon("src/Business/Util/Icon/Admin.png").getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT)));
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAdminIcn = new javax.swing.JLabel();
        TeamWorkspacePanel = new javax.swing.JPanel();
        btbTeamRequests = new javax.swing.JButton();
        btnSchedule = new javax.swing.JButton();
        btnManageChampionship = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        adminProfile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin's Workspace");

        lblAdminIcn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        TeamWorkspacePanel.setBackground(new java.awt.Color(255, 255, 255));
        TeamWorkspacePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Team Actions", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Avenir Next", 1, 14))); // NOI18N

        btbTeamRequests.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        btbTeamRequests.setText("Manage Team Requests");
        btbTeamRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbTeamRequestsActionPerformed(evt);
            }
        });

        btnSchedule.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        btnSchedule.setText("Manage Schedule");
        btnSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleActionPerformed(evt);
            }
        });

        btnManageChampionship.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        btnManageChampionship.setText("Manage Championships");
        btnManageChampionship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageChampionshipActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jButton2.setText("Update Standings");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeamWorkspacePanelLayout = new javax.swing.GroupLayout(TeamWorkspacePanel);
        TeamWorkspacePanel.setLayout(TeamWorkspacePanelLayout);
        TeamWorkspacePanelLayout.setHorizontalGroup(
            TeamWorkspacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeamWorkspacePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TeamWorkspacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageChampionship, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbTeamRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TeamWorkspacePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btbTeamRequests, btnManageChampionship, btnSchedule});

        TeamWorkspacePanelLayout.setVerticalGroup(
            TeamWorkspacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeamWorkspacePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btbTeamRequests)
                .addGap(18, 18, 18)
                .addComponent(btnSchedule)
                .addGap(18, 18, 18)
                .addComponent(btnManageChampionship)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        TeamWorkspacePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btbTeamRequests, btnManageChampionship, btnSchedule});

        adminProfile.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        adminProfile.setText("Manage Profile");
        adminProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminProfileActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Avenir Next", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Welcome!");

        date.setFont(new java.awt.Font("Avenir", 1, 24)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        date.setText("<Date Time>");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminProfile)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 488, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(TeamWorkspacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAdminIcn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(date)))
                .addContainerGap())
        );

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adminProfile, jButton1});

        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(TeamWorkspacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adminProfile)
                        .addGap(6, 6, 6)
                        .addComponent(jButton1))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblAdminIcn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void btbTeamRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbTeamRequestsActionPerformed
        // TODO add your handling code here:
            TeamRequestsJPanel tr = new TeamRequestsJPanel(container,ecosystem);
            container.add("teamRequests",tr);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"teamRequests");
    }//GEN-LAST:event_btbTeamRequestsActionPerformed

    private void btnScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleActionPerformed
        // TODO add your handling code here:
            ManageScheduleJPanel ms = new ManageScheduleJPanel(container,ecosystem);
            container.add("manageSchedule",ms);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"manageSchedule");
    }//GEN-LAST:event_btnScheduleActionPerformed

    private void btnManageChampionshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageChampionshipActionPerformed
        // TODO add your handling code here:
           ManageChampionshipJPanel mc = new ManageChampionshipJPanel(container,ecosystem);
            container.add("manageChampionship",mc);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"manageChampionship");
    }//GEN-LAST:event_btnManageChampionshipActionPerformed

    private void adminProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminProfileActionPerformed
        // TODO add your handling code here:
            AdminProfile ap = new AdminProfile(container,userAccount);
            container.add("adminProfile",ap);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"adminProfile");
    }//GEN-LAST:event_adminProfileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.first(container);
            db.storeSystem(ecosystem);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UpdateStandings us = new UpdateStandings(container,ecosystem);
            container.add("updateStandings",us);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"updateStandings");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TeamWorkspacePanel;
    private javax.swing.JButton adminProfile;
    private javax.swing.JButton btbTeamRequests;
    private javax.swing.JButton btnManageChampionship;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblAdminIcn;
    // End of variables declaration//GEN-END:variables
}
