/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdminRole;


import Sports.User.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anveshvarma
 */
public class AdminProfile extends javax.swing.JPanel {

    /**
     * Creates new form AdminProfile
     */
    JPanel container;
    UserAccount ua;
           
    public AdminProfile(JPanel container,UserAccount ua) {
        initComponents();
        this.container = container;
        this.ua = ua;
        lblUname.setText(ua.getUsername());
        lblbg.setIcon(new ImageIcon(new ImageIcon("src/Business/Util/Icon/Admin bg.png").getImage().getScaledInstance(592, 608, Image.SCALE_DEFAULT)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOldPwd = new javax.swing.JTextField();
        txtNewPwd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPwdUpdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        lblbg = new javax.swing.JLabel();
        lblUname = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(419, 333));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOldPwd.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        add(txtOldPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 172, 150, -1));

        txtNewPwd.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        add(txtNewPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 150, -1));

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Password:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 177, 96, -1));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Username:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 134, 96, -1));

        btnPwdUpdate.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        btnPwdUpdate.setText("Update");
        btnPwdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPwdUpdateActionPerformed(evt);
            }
        });
        add(btnPwdUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 268, -1, -1));

        jButton1.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        jLabel4.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Admin Profile");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 720, -1));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 153, 153));

        jLabel3.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("New Password:");

        lblUname.setFont(new java.awt.Font("Avenir", 0, 24)); // NOI18N
        lblUname.setForeground(new java.awt.Color(255, 255, 255));
        lblUname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUname.setText("<username>");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblUname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblbg, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(jLabel3))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(lblUname)))
                        .addGap(0, 370, Short.MAX_VALUE)))
                .addContainerGap())
        );

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPwdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPwdUpdateActionPerformed
        // TODO add your handling code here:
        if(txtOldPwd.getText().equals(ua.getPassword()))
        {
            if(txtNewPwd.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Enter new password");
            }
            else
            {
            ua.setPassword(txtNewPwd.getText());
            JOptionPane.showMessageDialog(this, "Password Update");
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Enter correct password");
    }//GEN-LAST:event_btnPwdUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"adminWorkspace");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPwdUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblUname;
    private javax.swing.JLabel lblbg;
    private javax.swing.JTextField txtNewPwd;
    private javax.swing.JTextField txtOldPwd;
    // End of variables declaration//GEN-END:variables
}
