/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdminRole;

import Business.EcoSystem;
import Business.Sport.Match;
import Business.Sport.Sport;
import Business.Sport.SportDirectory;
import java.awt.CardLayout;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author anveshvarma
 */
public class UpdateStandings extends javax.swing.JPanel {

    /**
     * Creates new form UpdateStandings
     */
    
        JPanel container;
    EcoSystem ecosystem;
    SportDirectory sd;
    public UpdateStandings(JPanel container,EcoSystem ecosystem) {
        this.container = container;
        this.ecosystem = ecosystem;
        sd = ecosystem.getEnterpriseDirectory().getSportsDirectory();
        initComponents();
        populateSelect();
        lblbg.setIcon(new ImageIcon(new ImageIcon("/Users/akhilrajeev/Desktop/AED/Commit/AEDProject/Icon/Admin bg.png").getImage().getScaledInstance(592, 608, Image.SCALE_DEFAULT)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        cmbSport = new javax.swing.JComboBox<>();
        cmbMatch = new javax.swing.JComboBox<>();
        txtTeams = new javax.swing.JTextField();
        cmbWinner = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnWinner = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblbg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 347, -1, -1));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 153, 153));

        cmbSport.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        cmbSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSportActionPerformed(evt);
            }
        });

        cmbMatch.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        cmbMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMatchActionPerformed(evt);
            }
        });

        txtTeams.setEditable(false);
        txtTeams.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        cmbWinner.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        cmbWinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbWinnerActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Teams:");

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Sport:");

        btnWinner.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        btnWinner.setText("Update");
        btnWinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWinnerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Winner:");

        jLabel2.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Match:");

        jLabel6.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Update Match Result");

        jButton1.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)
                                            .addComponent(cmbSport, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(36, 36, 36)
                                            .addComponent(cmbMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(btnWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(lblbg, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel5});

        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)
                        .addGap(66, 66, 66)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(37, 37, 37)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTeams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbWinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addComponent(btnWinner)
                        .addContainerGap(176, Short.MAX_VALUE))
                    .addComponent(lblbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSportActionPerformed
        // TODO add your handling code here:
        String sportName = (String) cmbSport.getSelectedItem();
        Sport sport = sd.getSport(sportName);
        ArrayList<Match> matches = sport.getMatches();
        DefaultComboBoxModel df = new DefaultComboBoxModel();
        for(Match m: matches)
        {
            df.addElement(m.getMatchNo());
        }
        cmbMatch.setModel(df);
         
    }//GEN-LAST:event_cmbSportActionPerformed

    private void cmbMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMatchActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel d = new DefaultComboBoxModel();
        String sportName = (String) cmbSport.getSelectedItem();
        String matchNo = String.valueOf(cmbMatch.getSelectedItem());
        Match match = sd.getMatch(matchNo,sportName);
        String team1 = match.getTeam1().getTeamName();
        String team2 = match.getTeam2().getTeamName();
        txtTeams.setText(""+team1+" vs "+team2);
        
        d.addElement(team1);
        d.addElement(team2);
        cmbWinner.setModel(d);
        
    }//GEN-LAST:event_cmbMatchActionPerformed

    private void btnWinnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWinnerActionPerformed
        // TODO add your handling code here:
        String sportName = (String) cmbSport.getSelectedItem();
        String matchNo = String.valueOf(cmbMatch.getSelectedItem());
        Match match = sd.getMatch(matchNo,sportName);
        String team1 = match.getTeam1().getTeamName();
        String team2 = match.getTeam2().getTeamName();
        String teamWon = (String) cmbWinner.getSelectedItem();
        match.setMatchWinner(teamWon);
        Sport sport = sd.getSport(sportName);
        sport.updatePoints(team1, team2, teamWon);
        txtTeams.setText("");
    }//GEN-LAST:event_btnWinnerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"adminWorkspace");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbWinnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbWinnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbWinnerActionPerformed

    private void populateSelect() {
        ArrayList<Sport> sports = sd.getSportsList();
        DefaultComboBoxModel df = new DefaultComboBoxModel();
        
        for(Sport s: sports)
        {
            df.addElement(s.getSportName());
        }
        cmbSport.setModel(df);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWinner;
    private javax.swing.JComboBox<String> cmbMatch;
    private javax.swing.JComboBox<String> cmbSport;
    private javax.swing.JComboBox<String> cmbWinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblbg;
    private javax.swing.JTextField txtTeams;
    // End of variables declaration//GEN-END:variables
}
