/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import Sports.DB40Util.DB4OUtil;
import Sports.Doctor.Doctor;
import Sports.Doctor.DoctorDirectory;
import Sports.EcoSystem;
import Sports.Employee.Employee;
import Sports.Logistics.Logistic;
import Sports.Role.DataAnalystRole;
import Sports.Role.DoctorRole;
import Sports.Role.EquipmentSupplierRole;
import Sports.Role.LogisticRole;
import Sports.Role.Role;
import Sports.Role.SponsorRole;
import Sports.Role.TeamManagerRole;
import Sports.Role.TravelTransportRole;
import Sports.Role.VenueManagerRole;
import Sports.Sponsor.Sponsor;
import Sports.Sponsor.SponsorDirectory;
import Sports.Sport.Sport;
import Sports.Sport.SportDirectory;
import Sports.Supplier.Supplier;
import Sports.Supplier.SupplierDirectory;
import Sports.Team.Team;
import Sports.TravelTransport.TravelTransport;
import Sports.User.UserAccount;
import Sports.User.UserAccountDirectory;
import Sports.Venue.Venue;
import Sports.Venue.VenueDirectory;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anveshvarma
 */
public class RegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterJPanel
     */
    DB4OUtil db = DB4OUtil.getInstance();
    EcoSystem ecoSystem;
    SportDirectory sportDirector;
    JPanel container;
    public RegisterJPanel(JPanel container,EcoSystem ecosystem) {
        initComponents();
        this.ecoSystem = ecosystem;
        this.container = container;
        sportDirector = ecosystem.getEnterpriseDirectory().getSportsDirectory();
        populateData();
        DoctorInfoPanel.setVisible(false);
                LogisticsPanel.setVisible(false);
                Supplier_SponsorPanel.setVisible(false);
                TeamManagerPanel.setVisible(false);
                VenuManagerPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReqAccess = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        BasicInfoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        DoctorInfoPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtDesignation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHsptl = new javax.swing.JTextField();
        TeamManagerPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTeam = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbSportSelect = new javax.swing.JComboBox<>();
        VenuManagerPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtVenue = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        LogisticsPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtLogisticCompany = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cmbLogisticType = new javax.swing.JComboBox<>();
        Supplier_SponsorPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtSponsorSupplier = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(706, 488));
        setMinimumSize(new java.awt.Dimension(720, 620));
        setPreferredSize(new java.awt.Dimension(720, 620));
        setSize(new java.awt.Dimension(706, 488));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReqAccess.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        btnReqAccess.setText("Request Access");
        btnReqAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqAccessActionPerformed(evt);
            }
        });
        add(btnReqAccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 6, -1, -1));

        Back.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 204, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 204, 204));

        BasicInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        BasicInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Basic Info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Avenir Next", 1, 14), new java.awt.Color(102, 0, 102))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Username:");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("E-mail ID:");

        javax.swing.GroupLayout BasicInfoPanelLayout = new javax.swing.GroupLayout(BasicInfoPanel);
        BasicInfoPanel.setLayout(BasicInfoPanelLayout);
        BasicInfoPanelLayout.setHorizontalGroup(
            BasicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BasicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BasicInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtName))
                    .addGroup(BasicInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsername))
                    .addGroup(BasicInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        BasicInfoPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5});

        BasicInfoPanelLayout.setVerticalGroup(
            BasicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicInfoPanelLayout.createSequentialGroup()
                .addGroup(BasicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        DoctorInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        DoctorInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Doctor's Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Avenir Next", 1, 14), new java.awt.Color(102, 0, 102))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Avenir", 1, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Designation:");

        txtDesignation.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Avenir", 1, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Hospital:");

        txtHsptl.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N

        javax.swing.GroupLayout DoctorInfoPanelLayout = new javax.swing.GroupLayout(DoctorInfoPanel);
        DoctorInfoPanel.setLayout(DoctorInfoPanelLayout);
        DoctorInfoPanelLayout.setHorizontalGroup(
            DoctorInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DoctorInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DoctorInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDesignation, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(txtHsptl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DoctorInfoPanelLayout.setVerticalGroup(
            DoctorInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorInfoPanelLayout.createSequentialGroup()
                .addGroup(DoctorInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(DoctorInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtHsptl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        TeamManagerPanel.setBackground(new java.awt.Color(255, 255, 255));
        TeamManagerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Team Manager", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Avenir Next", 1, 14), new java.awt.Color(102, 0, 102))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Team:");

        txtTeam.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel10.setText("Sport:");

        javax.swing.GroupLayout TeamManagerPanelLayout = new javax.swing.GroupLayout(TeamManagerPanel);
        TeamManagerPanel.setLayout(TeamManagerPanelLayout);
        TeamManagerPanelLayout.setHorizontalGroup(
            TeamManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeamManagerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TeamManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeamManagerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTeam))
                    .addGroup(TeamManagerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSportSelect, 0, 129, Short.MAX_VALUE)))
                .addContainerGap())
        );

        TeamManagerPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel9});

        TeamManagerPanelLayout.setVerticalGroup(
            TeamManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeamManagerPanelLayout.createSequentialGroup()
                .addGroup(TeamManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TeamManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbSportSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        VenuManagerPanel.setBackground(new java.awt.Color(255, 255, 255));
        VenuManagerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Venue Manager", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Avenir Next", 1, 14), new java.awt.Color(102, 0, 102))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel13.setText("Venue:");

        txtVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVenueActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel14.setText("City:");

        jLabel15.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel15.setText("State:");

        javax.swing.GroupLayout VenuManagerPanelLayout = new javax.swing.GroupLayout(VenuManagerPanel);
        VenuManagerPanel.setLayout(VenuManagerPanelLayout);
        VenuManagerPanelLayout.setHorizontalGroup(
            VenuManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenuManagerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VenuManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VenuManagerPanelLayout.createSequentialGroup()
                        .addGroup(VenuManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VenuManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCity)
                            .addComponent(txtState)))
                    .addGroup(VenuManagerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        VenuManagerPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel14, jLabel15});

        VenuManagerPanelLayout.setVerticalGroup(
            VenuManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenuManagerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VenuManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VenuManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VenuManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        LogisticsPanel.setBackground(new java.awt.Color(255, 255, 255));
        LogisticsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Logistics/Travel", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Avenir Next", 1, 13), new java.awt.Color(102, 0, 102))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Company:");

        txtLogisticCompany.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel18.setText("*Type:");

        jLabel19.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("* Cargo or Travel");

        cmbLogisticType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cargo", "Travel" }));

        javax.swing.GroupLayout LogisticsPanelLayout = new javax.swing.GroupLayout(LogisticsPanel);
        LogisticsPanel.setLayout(LogisticsPanelLayout);
        LogisticsPanelLayout.setHorizontalGroup(
            LogisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogisticsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LogisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LogisticsPanelLayout.createSequentialGroup()
                        .addGroup(LogisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LogisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLogisticCompany)
                            .addComponent(cmbLogisticType, 0, 104, Short.MAX_VALUE))))
                .addContainerGap())
        );

        LogisticsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel17, jLabel18});

        LogisticsPanelLayout.setVerticalGroup(
            LogisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogisticsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LogisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtLogisticCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LogisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cmbLogisticType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Supplier_SponsorPanel.setBackground(new java.awt.Color(255, 255, 255));
        Supplier_SponsorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sponsor/Equipment Supplier", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Avenir Next", 1, 13), new java.awt.Color(102, 0, 102))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Company:");

        javax.swing.GroupLayout Supplier_SponsorPanelLayout = new javax.swing.GroupLayout(Supplier_SponsorPanel);
        Supplier_SponsorPanel.setLayout(Supplier_SponsorPanelLayout);
        Supplier_SponsorPanelLayout.setHorizontalGroup(
            Supplier_SponsorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Supplier_SponsorPanelLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSponsorSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Supplier_SponsorPanelLayout.setVerticalGroup(
            Supplier_SponsorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Supplier_SponsorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Supplier_SponsorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSponsorSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Select Role:");

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data Analyst", "Doctor", "Logistics", "Supplier", "Sponsor", "Sports Admin", "Team Manager", "Venue Manager", " ", " " }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Registration");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(BasicInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DoctorInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TeamManagerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(Supplier_SponsorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(VenuManagerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LogisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeamManagerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BasicInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VenuManagerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Supplier_SponsorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:

          CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.first(container);
    }//GEN-LAST:event_BackActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
        String cmbindex = (String) cmbRole.getSelectedItem();
        switch(cmbindex){
          
            case "Data Analyst": 
                DoctorInfoPanel.setVisible(false);
                LogisticsPanel.setVisible(false);
                Supplier_SponsorPanel.setVisible(false);
                TeamManagerPanel.setVisible(false);
                VenuManagerPanel.setVisible(false);
                break;
            
            case "Doctor":
                DoctorInfoPanel.setVisible(true);
                LogisticsPanel.setVisible(false);
                Supplier_SponsorPanel.setVisible(false);
                TeamManagerPanel.setVisible(false);
                VenuManagerPanel.setVisible(false);
                break;
                
            case "Logistics":
                DoctorInfoPanel.setVisible(false);
                LogisticsPanel.setVisible(true);
                Supplier_SponsorPanel.setVisible(false);
                TeamManagerPanel.setVisible(false);
                VenuManagerPanel.setVisible(false);
                break;
                
            case "Supplier":
                DoctorInfoPanel.setVisible(false);
                LogisticsPanel.setVisible(false);
                Supplier_SponsorPanel.setVisible(true);
                TeamManagerPanel.setVisible(false);
                VenuManagerPanel.setVisible(false);
                break;
                
            case "Sponsor":
                DoctorInfoPanel.setVisible(false);
                LogisticsPanel.setVisible(false);
                Supplier_SponsorPanel.setVisible(true);
                TeamManagerPanel.setVisible(false);
                VenuManagerPanel.setVisible(false);
                break;
             
            case "Sports Admin": 
                DoctorInfoPanel.setVisible(false);
                LogisticsPanel.setVisible(false);
                Supplier_SponsorPanel.setVisible(false);
                TeamManagerPanel.setVisible(false);
                VenuManagerPanel.setVisible(false);
                break;
                
            case "Team Manager": 
                DoctorInfoPanel.setVisible(false);
                LogisticsPanel.setVisible(false);
                Supplier_SponsorPanel.setVisible(false);
                TeamManagerPanel.setVisible(true);
                VenuManagerPanel.setVisible(false);
                break;
                
            case "Venue Manager": 
                DoctorInfoPanel.setVisible(false);
                LogisticsPanel.setVisible(false);
                Supplier_SponsorPanel.setVisible(false);
                TeamManagerPanel.setVisible(false);
                VenuManagerPanel.setVisible(true);
                break;
                
            default:
                DoctorInfoPanel.setVisible(false);
                LogisticsPanel.setVisible(false);
                Supplier_SponsorPanel.setVisible(false);
                TeamManagerPanel.setVisible(false);
                VenuManagerPanel.setVisible(true);
                break;
        }
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void txtVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVenueActionPerformed

    private void btnReqAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqAccessActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory ud = ecoSystem.getUserAccountDirectory();
        Role role;
        String roleSelect = (String) cmbRole.getSelectedItem();
        DoctorDirectory dd = ecoSystem.getEnterpriseDirectory().getDoctorDirectory();
       
        VenueDirectory vd = ecoSystem.getEnterpriseDirectory().getVenueDirectory();
        SupplierDirectory suppDir = ecoSystem.getEnterpriseDirectory().getSupplierDirectory();
        
        
        SponsorDirectory sponsorD = ecoSystem.getEnterpriseDirectory().getSponsorDirectory();
        

        
        UserAccount ua;
        Employee employee = new Employee();
        employee.setName(txtName.getText());
        boolean fieldsEmpty = false;
        if(txtName.getText().equals("") || txtUsername.getText().equals("") || txtEmail.getText().equals(""))
        {
                   fieldsEmpty = true;
        }
        boolean uniqueUname = ud.checkIfUsernameIsUnique(txtUsername.getText());
        if(uniqueUname)
        {
            if(!fieldsEmpty)
            {
               if(roleSelect.equals("Doctor"))
                {
                   role = new DoctorRole();
                   ua = ud.accessUseraccountRequest(txtUsername.getText(), employee, role);
                   ua.setEmail(txtEmail.getText());
                   Doctor doctor=null;
                   try {
                       doctor = new Doctor(ua,txtName.getText(),txtDesignation.getText());
                   } catch (ParseException ex) {
                       Logger.getLogger(RegisterJPanel.class.getName()).log(Level.SEVERE, null, ex);
                   }
                   dd.addDoctor(doctor);
                   
                }
               if(roleSelect.equals("Venue Manager"))
                {
                   role = new VenueManagerRole();
                   ua = ud.accessUseraccountRequest(txtUsername.getText(), employee, role);
                   ua.setEmail(txtEmail.getText());
                   Venue venue = new Venue(ua,txtVenue.getText(),txtCity.getText());
                   vd.addVenue(venue);
                }
               if(roleSelect.equals("Equipment Supplier"))
                {
                   role = new EquipmentSupplierRole();
                   ua = ud.accessUseraccountRequest(txtUsername.getText(), employee, role);
                   ua.setEmail(txtEmail.getText());
                   Supplier supplier = new Supplier(ua,txtSponsorSupplier.getText());
                   suppDir.addSupplier(supplier);
                }
               if(roleSelect.equals("Sponsor"))
                {
                   role = new SponsorRole();
                   ua = ud.accessUseraccountRequest(txtUsername.getText(), employee, role);
                   ua.setEmail(txtEmail.getText());
                   Sponsor sponsor = new Sponsor(ua,txtSponsorSupplier.getText());
                   sponsorD.addSponsor(sponsor);
                }
               if(roleSelect.equals("Sports Admin"))
                {
                   ua = ud.addAdminAccess(txtUsername.getText(), employee);
                   ua.setEmail(txtEmail.getText());
                }
                if(roleSelect.equals("Team Manager"))
                {
                   role = new TeamManagerRole();
                   ua = ud.accessUseraccountRequest(txtUsername.getText(), employee, role);
                   ua.setEmail(txtEmail.getText());
                   Sport sport = sportDirector.getSport((String) cmbSportSelect.getSelectedItem());
                   Team team = new Team(ua, txtTeam.getText());
                   team.setTeamManager(employee.getName());
                   
                   sport.addTeamRequest(team);
                }
                
                if(roleSelect.equals("Supplier"))
                {
                   role = new EquipmentSupplierRole();
                   ua = ud.accessUseraccountRequest(txtUsername.getText(), employee, role);
                   ua.setEmail(txtEmail.getText());
                   Supplier supplier = new Supplier(ua, txtSponsorSupplier.getText());
                   suppDir.addSupplier(supplier);
                }
                
                if(roleSelect.equals("Data Analyst"))
                {
                   role = new DataAnalystRole();
                   ua = ud.accessUseraccountRequest(txtUsername.getText(), employee, role);
                   ua.setEmail(txtEmail.getText());
                }
                
                if(roleSelect.equals("Logistics"))
                {
                    if(((String) cmbLogisticType.getSelectedItem()).equals("Cargo"))
                    {
                   role = new LogisticRole();
                   ua = ud.accessUseraccountRequest(txtUsername.getText(), employee, role);
                   ua.setEmail(txtEmail.getText());
                   Logistic logistic = new Logistic(ua, txtLogisticCompany.getText(), txtName.getText());
                   suppDir.addLogist(logistic);
                    }
                    else
                    {
                       role = new TravelTransportRole();
                   ua = ud.accessUseraccountRequest(txtUsername.getText(), employee, role);
                   ua.setEmail(txtEmail.getText());
                   TravelTransport tt = new TravelTransport(ua, txtLogisticCompany.getText());
                   suppDir.addTravelTransport(tt);
                    }
                    
                }
                
               JOptionPane.showMessageDialog(this, "Request sent");
             }
            else
                JOptionPane.showMessageDialog(this, "Please fill required details");
        }   
        else
            JOptionPane.showMessageDialog(this, "Username already exists");
        
        db.storeSystem(ecoSystem);
        txtCity.setText("");
        txtDesignation.setText("");
        txtEmail.setText("");
        txtHsptl.setText("");
        txtLogisticCompany.setText("");
        txtName.setText("");
        txtSponsorSupplier.setText("");
        txtState.setText("");
        txtTeam.setText("");
        txtUsername.setText("");
        txtVenue.setText("");
        
        
        
    }//GEN-LAST:event_btnReqAccessActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPanel BasicInfoPanel;
    private javax.swing.JPanel DoctorInfoPanel;
    private javax.swing.JPanel LogisticsPanel;
    private javax.swing.JPanel Supplier_SponsorPanel;
    private javax.swing.JPanel TeamManagerPanel;
    private javax.swing.JPanel VenuManagerPanel;
    private javax.swing.JButton btnReqAccess;
    private javax.swing.JComboBox<String> cmbLogisticType;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JComboBox<String> cmbSportSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDesignation;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHsptl;
    private javax.swing.JTextField txtLogisticCompany;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSponsorSupplier;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTeam;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtVenue;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
        ArrayList<Sport> sportList = sportDirector.getSportsList();
        DefaultComboBoxModel df = new DefaultComboBoxModel();
        for(Sport s: sportList)
        {
            df.addElement(s.getSportName());
        }
        cmbSportSelect.setModel(df);
    }
}
