/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.VenueManagerRole;


import Sports.DB40Util.DB4OUtil;
import Sports.EcoSystem;
import Sports.User.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.time.LocalTime;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author anveshvarma
 */
public class VenueManagerWorkspace extends javax.swing.JPanel {

    /**
     * Creates new form VenueManagerWorkspace
     */
    DB4OUtil db = DB4OUtil.getInstance();
    JPanel container;
    EcoSystem ecosystem;
    UserAccount ua;
    public VenueManagerWorkspace(JPanel container,UserAccount ua, EcoSystem ecosystem) {
        initComponents();
        date.setText(" "+String.valueOf(LocalTime.now().getHour()) + ":"+String.valueOf(LocalTime.now().getMinute()));
        this.container = container;
        this.ecosystem = ecosystem;
        this.ua = ua;
        lblvnu.setIcon(new ImageIcon(new ImageIcon("src/Business/Util/Icon/Venue.png").getImage().getScaledInstance(250, 250, Image.SCALE_DEFAULT)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        btnVenueRequests = new javax.swing.JButton();
        btnVenueScd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        lblvnu = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(720, 460));
        setPreferredSize(new java.awt.Dimension(1620, 1050));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Venue Manager Workspace");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 51, 710, -1));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 204, 204));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(720, 460));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(720, 460));

        jLabel6.setFont(new java.awt.Font("Avenir Next", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Welcome!");

        btnVenueRequests.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        btnVenueRequests.setText("Venue Requests");
        btnVenueRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenueRequestsActionPerformed(evt);
            }
        });

        btnVenueScd.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        btnVenueScd.setText("View Scheduled Matches");
        btnVenueScd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenueScdActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("Avenir", 1, 24)); // NOI18N
        date.setForeground(new java.awt.Color(153, 0, 51));
        date.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        date.setText("<Date Time>");

        lblvnu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvnu.setPreferredSize(new java.awt.Dimension(310, 270));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVenueRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVenueScd, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(lblvnu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date)
                .addGap(88, 88, 88)
                .addComponent(jLabel6)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnVenueRequests)
                        .addGap(18, 18, 18)
                        .addComponent(btnVenueScd)
                        .addGap(28, 28, 28)
                        .addComponent(jButton1))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblvnu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVenueRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenueRequestsActionPerformed
        // TODO add your handling code here:
          VenueRequestsJPanel vr = new VenueRequestsJPanel(container, ua, ecosystem);
          container.add("venueRequests",vr);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"venueRequests");
    }//GEN-LAST:event_btnVenueRequestsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.first(container);
            db.storeSystem(ecosystem);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVenueScdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenueScdActionPerformed
        // TODO add your handling code here:
        ViewScheduledMatchesJPanel vs = new ViewScheduledMatchesJPanel(container, ua, ecosystem);
          container.add("venueRequests",vs);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"venueRequests");
    }//GEN-LAST:event_btnVenueScdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVenueRequests;
    private javax.swing.JButton btnVenueScd;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblvnu;
    // End of variables declaration//GEN-END:variables
}
